apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flask-ecommerce-development

# Base configuration
resources:
  - ../../

# Namespace override
namespace: flask-ecommerce-dev

# Development-specific labels
commonLabels:
  environment: development

# Development image tags
images:
  - name: flask-ecommerce
    newTag: dev-latest

# Development replicas (fewer for cost)
replicas:
  - name: flask-app-deployment
    count: 1
  - name: nginx-deployment
    count: 1

# Development patches
patchesStrategicMerge:
  - dev-patches.yaml

# Development config
configMapGenerator:
  - name: flask-app-env
    behavior: replace
    literals:
      - FLASK_ENV=development
      - FLASK_DEBUG=True
      - LOG_LEVEL=DEBUG
