apiVersion: v1
kind: ConfigMap
metadata:
  name: flask-app-config
  namespace: flask-ecommerce
data:
  FLASK_ENV: "production"
  FLASK_DEBUG: "False"
  PORT: "5000"
  DATABASE_URL: "sqlite:///data/production.db"
  LOG_LEVEL: "INFO"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
  namespace: flask-ecommerce
data:
  nginx.conf: |
    events {
        worker_connections 1024;
    }
    
    http {
        upstream flask_app {
            server flask-app-service:5000;
        }
        
        server {
            listen 80;
            server_name _;
            
            location / {
                proxy_pass http://flask_app;
                proxy_set_header Host $host;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header X-Forwarded-Proto $scheme;
                proxy_connect_timeout 30s;
                proxy_send_timeout 30s;
                proxy_read_timeout 30s;
            }
            
            location /static/ {
                proxy_pass http://flask_app/static/;
                expires 30d;
                add_header Cache-Control "public, no-transform";
            }
            
            location /health {
                proxy_pass http://flask_app/;
                access_log off;
            }
        }
    }
