apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: flask-db-pvc
  namespace: flask-ecommerce
  annotations:
    # AWS EBS specific annotations
    volume.beta.kubernetes.io/storage-class: "gp2"
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
  storageClassName: gp2
