apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "flask-ecommerce.fullname" . }}-config
  labels:
    {{- include "flask-ecommerce.labels" . | nindent 4 }}
data:
  FLASK_ENV: {{ .Values.env | default "production" | quote }}
  FLASK_DEBUG: "false"
  LOG_LEVEL: "INFO"
  SESSION_TIMEOUT: "3600"
  MAX_CONTENT_LENGTH: "16777216"
  UPLOAD_FOLDER: "/app/uploads"
  ALLOWED_EXTENSIONS: "png,jpg,jpeg,gif"
