apiVersion: v1
kind: Secret
metadata:
  name: {{ include "flask-ecommerce.fullname" . }}-secret
  labels:
    {{- include "flask-ecommerce.labels" . | nindent 4 }}
type: Opaque
data:
  secret-key: {{ randAlphaNum 32 | b64enc | quote }}
  database-url: {{ include "flask-ecommerce.databaseUrl" . | b64enc | quote }}
  redis-url: {{ include "flask-ecommerce.redisUrl" . | b64enc | quote }}
