apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: flask-ecommerce-production

# Base configuration
resources:
  - ../../

# Production namespace
namespace: flask-ecommerce

# Production-specific labels
commonLabels:
  environment: production

# Production image tags
images:
  - name: flask-ecommerce
    newTag: v1.0.0

# Production replicas (high availability)
replicas:
  - name: flask-app-deployment
    count: 5
  - name: nginx-deployment
    count: 3

# Production patches
patchesStrategicMerge:
  - prod-patches.yaml

# Production config
configMapGenerator:
  - name: flask-app-env
    behavior: replace
    literals:
      - FLASK_ENV=production
      - FLASK_DEBUG=False
      - LOG_LEVEL=INFO
      - WORKERS=4
      - THREADS=2
