apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-app-deployment
spec:
  template:
    spec:
      containers:
      - name: flask-app
        resources:
          requests:
            memory: "1Gi"
            cpu: "750m"
          limits:
            memory: "2Gi"
            cpu: "1500m"
        env:
        - name: WORKERS
          value: "4"
        - name: THREADS
          value: "2"
        - name: FLASK_DEBUG
          value: "False"
        - name: LOG_LEVEL
          value: "INFO"
      nodeSelector:
        kubernetes.io/os: linux
        node-type: application
      tolerations:
      - key: "application"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: flask-app-hpa
spec:
  minReplicas: 3
  maxReplicas: 20
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 60
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 70
