version: '3.8'
services:
  flask_api:
    build: ./flask_api
    ports:
      - "5000:5000"
    volumes:
      - ./model:/app/model
    depends_on:
      - prometheus
  ab_testing:
    build: ./ab_testing
    ports:
      - "6000:6000"
    depends_on:
      - flask_api
  streamlit_app:
    build: ./streamlit_app
    ports:
      - "8501:8501"
    depends_on:
      - flask_api
      - ab_testing
  prometheus:
    image: prom/prometheus
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
