apiVersion: v2
name: flask-ecommerce
description: A Helm chart for Flask E-commerce Application
type: application
version: 1.0.0
appVersion: "1.0.0"
keywords:
  - flask
  - ecommerce
  - python
  - web
home: https://github.com/yourusername/flask-ecommerce
sources:
  - https://github.com/yourusername/flask-ecommerce
maintainers:
  - name: DevOps Team
    email: devops@company.com
dependencies:
  - name: postgresql
    version: "11.9.13"
    repository: "https://charts.bitnami.com/bitnami"
    condition: postgresql.enabled
  - name: redis
    version: "17.3.7"
    repository: "https://charts.bitnami.com/bitnami"
    condition: redis.enabled
annotations:
  category: Application
